

# ── General ─────────────────────────────────────────────────────────────────────
set -g prefix ^A
set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on
set -g mouse on
set -g mode-keys vi
set -sg escape-time 0
set -g history-limit 1000000
set -g detach-on-destroy off
set -g set-clipboard on
set -g status-position top

# ── Key bindings ─────────────────────────────────────────────────────────────────
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
# Sesh
bind-key "T" display-popup -E -w 80% -h 70% -d '#{pane_current_path}' -T 'Sesh' tv sesh


# ── Terminal ────────────────────────────────────────────────────────────────────
set-option -g default-terminal 'screen-256color'
set-option -g terminal-overrides ',xterm-256color:RGB'

# ── Plugins ──────────────────────────────────────────────────────────────────────
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

# tmux-autoreload
# See: https://github.com/b0o/tmux-autoreload
set -g @plugin 'b0o/tmux-autoreload'
set -g @tmux-autoreload-configs '/Users/tadeas.bronis/.config/tmux/tmux.conf'
set -g @tmux-autoreload-entrypoints '/Users/tadeas.bronis/.config/tmux/tmux.conf'

# ── Dracula ───────────────────────────────────────────────────────────────────────
# See: https://github.com/dracula/tmux/blob/master/docs/CONFIG.md
set -g @plugin 'dracula/tmux'

# Status bar
set -g @dracula-plugins " "
set -g @dracula-show-empty-plugins false
set -g @dracula-border-contrast true
set -g @dracula-left-pad ' ○ '
set -g @dracula-right-pad ' ○ '

# Powerline
set -g @dracula-show-flags true
set -g @dracula-show-powerline true
set -g @dracula-show-edge-icons true
set -g @dracula-show-left-sep "\uE0B4"
set -g @dracula-show-right-sep "\uE0B6"
set -g @dracula-transparent-powerline-bg true

# Left icon
set -g @dracula-show-left-icon "\uedc5 | #S"

# ── TPM · Initialize ─────────────────────────────────────────────────────────────
# ⚠ NOTE: keep at the very bottom
# See: https://github.com/tmux-plugins/tpm/blob/master/docs/changing_plugins_install_dir.md
set-environment -g TMUX_PLUGIN_MANAGER_PATH '~/.tmux/plugins/'
# See: https://github.com/tmux-plugins/tpm/blob/master/docs/automatic_tpm_installation.md
if "test ! -d ~/.tmux/plugins/tpm" \
   "run 'git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm && ~/.tmux/plugins/tpm/bin/install_plugins'"
run '~/.tmux/plugins/tpm/tpm'
